const ROLES = [
    'killer',
    'survivor'
];

const SURVIVORS = [
    'dwight',
    'meg',
    'claudette',
    'jake',
    'jeff',
    'nea',
    'bill',
    'david',
    'laurie',
    'ace',
    'feng',
    'quentin',
    'tapp',
    'kate',
    'francis',
    'jane',
    'ash',
    'nancy',
    'steve',
    'kimura',
    'zarina',
    'cheryl',
    'felix',
    'elodie',
    'jill',
    'yun-jin',
    'leon',
    'mikaela',
    'jonah'    
]; // list of all available survivors

const KILLERS = [
    'clown',
    'doctor',
    'freddy',
    'hag',
    'hillbilly',
    'huntress',
    'leatherface',
    'legion',
    'myers',
    'nurse',
    'pig',
    'spirit',
    'trapper',
    'wraith',
    'plague',
    'ghostface',
    'demogorgon',
    'oni',
    'deathslinger',
    'executioner',
    'blight',
    'twins',
    'trickster',
    'nemesis',
    'cenobite',
    'artist'
]; // list of all available killers

const KILLER_PERKS = [
    'agitation',
    'aNursesCalling',
    'bamboozle',
    'BBQAndChili',
    'BeastOfPrey',
    'bitterMurmur',
    'bloodhound',
    'bloodWarden',
    'brutalStrength',
    'coulrophobia',
    'deerstalker',
    'devourHope',
    'discordance',
    'distressing',
    'dyingLight',
    'enduring',
    'fireUp',
    'franklinsLoss',
    'generatorOvercharge',
    'hangmansTrick',
    'hatred',
    'hauntedGround',
    'HuntressLullaby',
    'insidious',
    'ironGrasp',
    'ironMaiden',
    'knockOut',
    'lightborn',
    'madGrit',
    'makeYourChoice',
    'monitorAndAbuse',
    'monstrousShrine',
    'noOneEscapesDeath',
    'overwhelmingPresence',
    'playWithYourFood',
    'popGoesTheWeasel',
    'predator',
    'rememberMe',
    'ruin',
    'saveTheBestForLast',
    'shadowborn',
    'sloppyButcher',
    'spiesFromTheShadows',
    'spiritFury',
    'stridor',
    'surveillance',
    'territorialImperative',
    'thatanophobia',
    'theThirdSeal',
    'thrillOfTheHunt',
    'tinkerer',
    'unnervingPresence',
    'unrelenting',
    'whispers',
    'corruptIntervention',
    'infectiousFright',
    'darkDevotion',
    'furtiveChase',
    'imAllEars',
    'thrillingTremors',
    'clautrophobia',
    'fearmonger',
    'jolt',
    'bloodEcho',
    'nemesis',
    'zanshinTactics',
    'deadManSwitch',
    'gearHead',
    'hexRetribution',
    'deathbound',
    'forcedPenance',
    'trailOfTorment',
    'dragonsGrip',
    'hexBloodFavor',
    'hexUndying',
    'oppression',
    'hoarder',
    'coupDeGrace',
    'starstruck',
    'hexCrownControl',
    'noWayOut',
    'lethalPersuer',
    'hysteria',
    'eruption',
    'deadlock',
    'hexPlaything',
    'scourgeHookGiftofPain',
    'grimEmbrace',
    'scourgeHookPainResonance',
    'hexPentimento'
]; // list of all killers perks

const SURVIVOR_PERKS = [
    'aceInTheHole',
    'adrenaline',
    'aftercare',
    'alert',
    'autodidact',
    'balancedLanding',
    'boilOver',
    'bond',
    'borrowedTime',
    'botanyKnowledge',
    'breakdown',
    'calmSpirit',
    'danceWithMe',
    'darkSense',
    'DeadHard',
    'decisiveStrike',
    'dejaVu',
    'deliverance',
    'detectivesHunch',
    'distortion',
    'diversion',
    'empathy',
    'hope',
    'ironWill',
    'kindred',
    'leader',
    'leftBehind',
    'lightweight',
    'lithe',
    'NoMither',
    'noOneLeftBehind',
    'objectOfObsession',
    'openHanded',
    'pharmacy',
    'plunderersInstinct',
    'premonition',
    'proveThyself',
    'quickAndQuiet',
    'resilience',
    'saboteur',
    'selfCare',
    'slipperyMeat',
    'smallGame',
    'soleSurvivor',
    'spineChill',
    'sprintBurst',
    'stakeOut',
    'streetwise',
    'technician',
    'tenacity',
    'thisIsNotHappening',
    'unbreakable',
    'upTheAnte',
    'urbanEvasion',
    'vigil',
    'wakeUp',
    'wellMakeIt',
    'WereGonnaLiveForever',
    'windowsOfOpportunity',
    'headOn',
    'poised',
    'solidarity',
    'buckleUp',
    'flipFlop',
    'mettleOfMan',
    'guardian',
    'situationalAwareness',
    'kinship',
    'selfAware',
    'innerHealing',
    'renewal',
    'anyMeansNecessary',
    'breakout',
    'luckyBreak',
    'forThePeople',
    'offTheRecord',
    'redHerring',
    'bloodPact',
    'repressedAlliance',
    'soulGuard',
    'visionary',
    'builtToLast',
    'desperateMeasures',
    'powerStruggle',
    'deception',
    'appraisal',
    'smashHit',
    'smartTrack',
    'selfPreservation',
    'resurgence',
    'blastMine',
    'counterforce',
    'flashBang',
    'biteTheBullet',
    'rookieSpirit',
    'clairvoyance',
    'boonCircleOfHealing',
    'boonShadowStep',
    'overcome',
    'correctiveAction',
    'boonExponential'
]; // list of all survivor perks

const RARE_PERKS = [];

const KILLER_POWERS = {
    'clown': {
        image: 'gasBomb',
        addons: [
            { name: 'Smelly Inner Soles', image: 'smellyInnerSoles', rarity: 'common' },
            { name: 'Robin Feather', image: 'robinFeather', rarity: 'common' },
            { name: 'Fingerless Parade Gloves', image: 'fingerlessParadeGloves', rarity: 'common' },
            { name: 'Ether 5 Vol%', image: 'ether5', rarity: 'common' },
            { name: 'Thick Cork Stopper', image: 'thickCorkStopper', rarity: 'uncommon' },
            { name: 'Sticky Soda Bottle', image: 'stickySodaBottle', rarity: 'uncommon' },
            { name: 'Starling Feather', image: 'starlingFeather', rarity: 'uncommon' },
            { name: 'Solvent Jug', image: 'solventJug', rarity: 'uncommon' },
            { name: 'Kerosene Can', image: 'keroseneCan', rarity: 'uncommon' },
            { name: 'VHS Porn', image: 'vhsPorn', rarity: 'rare' },
            { name: 'Sulphuric Acid Vial', image: 'sulfuricAcidVial', rarity: 'rare' },
            { name: 'Flask Of Bleach', image: 'flaskOfBleach', rarity: 'rare' },
            { name: 'Ether 10 Vol%', image: 'ether10', rarity: 'rare' },
            { name: 'Bottle Of Chloroform', image: 'bottleOfChloroform', rarity: 'rare' },
            { name: 'Garish Make-up Kit', image: 'garishMakeupKit', rarity: 'veryrare' },
            { name: 'Ether 15 Vol%', image: 'ether15', rarity: 'veryrare' },
            { name: 'Cigar Box', image: 'cigarBox', rarity: 'veryrare' },
            { name: 'Cheap Gin Bottle', image: 'cheapGinBottle', rarity: 'veryrare' },
            { name: 'Tattoo\'s Middle Finger', image: 'tattoosMiddleFinger', rarity: 'ultra' },
            { name: 'Redhead\'s Pinky Finger', image: 'redheadsPinkyFinger', rarity: 'ultra' }
        ]
    },
    'doctor': {
        image: 'cartersSpark',
        addons: [
            { name: 'Mouldy Electrode', image: 'moldyElectrode', rarity: 'common' },
            { name: 'Maple Knight', image: 'mapleKnight', rarity: 'common' },
            { name: '"Order" - Class I', image: 'orderClassI', rarity: 'common' },
            { name: '"Calm" - Class I', image: 'calmClassI', rarity: 'common' },
            { name: 'Scrapped Tape', image: 'scrappedTape', rarity: 'uncommon' },
            { name: 'Polished Electrode', image: 'polishedElectrode', rarity: 'uncommon' },
            { name: 'Interview Tape', image: 'interviewTape', rarity: 'uncommon' },
            { name: '"Restraint" - Class II', image: 'restraintClassII', rarity: 'uncommon' },
            { name: '"Order" - Class II', image: 'diciplineClassII', rarity: 'uncommon' },
            { name: '"Discipline" - Class II', image: 'orderClassII', rarity: 'uncommon' },
            { name: '"Calm" - Class II', image: 'calmClassII', rarity: 'uncommon' },
            { name: 'High Stimulus Electrode', image: 'highStimulusElectrode', rarity: 'rare' },
            { name: '"Restraint" - Class III', image: 'restraintClassIII', rarity: 'rare' },
            { name: '"Discipline" - Class III', image: 'diciplineClassIII', rarity: 'rare' },
            { name: '"Restraint" - Carter\'s Notes', image: 'restraintCartersNotes', rarity: 'veryrare' },
            { name: '"Order" - Carter\'s Notes', image: 'orderCartersNotes', rarity: 'veryrare' },
            { name: '"Obedience" - Carter\'s Notes', image: 'obedienceCartersNotes', rarity: 'veryrare' },
            { name: '"Discipline" - Carter\'s Notes', image: 'diciplineCartersNotes', rarity: 'veryrare' },
            { name: '"Calm" - Carter\'s Notes', image: 'calmCartersNotes', rarity: 'veryrare' },
            { name: 'Iridescent King', image: 'iridescentKing', rarity: 'ultra' }
        ]
    },
    'freddy': {
        image: 'dreamMaster',
        addons: [
            { name: 'Wool Shirt', image: 'woolShirt', rarity: 'common' },
            { name: 'Sheep Block', image: 'sheepBlock', rarity: 'common' },
            { name: 'Kid\'s Drawing', image: 'kidsDrawing', rarity: 'common' },
            { name: 'Garden Rake', image: 'gardenRake', rarity: 'common' },
            { name: 'Prototype Claws', image: 'prototypeClaw', rarity: 'uncommon' },
            { name: 'Outdoor Rope', image: 'outdoorRope', rarity: 'uncommon' },
            { name: 'Nancy\'s Sketch', image: 'nancysSketch', rarity: 'uncommon' },
            { name: 'Green Dress', image: 'greenDress', rarity: 'uncommon' },
            { name: 'Cat Block', image: 'catBlock', rarity: 'uncommon' },
            { name: 'Unicorn Block', image: 'unicornBlock', rarity: 'rare' },
            { name: 'Swing Chains', image: 'swingChains', rarity: 'rare' },
            { name: 'Nancy\'s Masterpiece', image: 'nancysMasterpiece', rarity: 'rare' },
            { name: 'Jump Rope', image: 'jumpRope', rarity: 'rare' },
            { name: 'Blue Dress', image: 'blueDress', rarity: 'rare' },
            { name: 'Pill Bottle', image: 'pillBottle', rarity: 'veryrare' },
            { name: 'Paint Thinner', image: 'paintThinner', rarity: 'veryrare' },
            { name: 'Class Photo', image: 'classPhoto', rarity: 'veryrare' },
            { name: '"Z" Block', image: 'zBlock', rarity: 'veryrare' },
            { name: 'Red Paint Brush', image: 'redPaintBrush', rarity: 'ultra' },
            { name: 'Black Box', image: 'blackBox', rarity: 'ultra' }
        ]
    },
    'hag': {
        image: 'blackenedCatalyst',
        addons: [
            { name: 'Rope Necklet', image: 'ropeNecklet', rarity: 'common' },
            { name: 'Powdered Eggshell', image: 'powderedEggshell', rarity: 'common' },
            { name: 'Dead Fly Mud', image: 'deadFlyMud', rarity: 'common' },
            { name: 'Bog Water', image: 'bogWater', rarity: 'common' },
            { name: 'Pussy Willow Catkins', image: 'pussyWillowCatkins', rarity: 'uncommon' },
            { name: 'Half Eggshell', image: 'halfEggshell', rarity: 'uncommon' },
            { name: 'Dragonfly Wings', image: 'dragonflyWings', rarity: 'uncommon' },
            { name: 'Cypress Necklet', image: 'cypressNecklet', rarity: 'uncommon' },
            { name: 'Bloodied Water', image: 'bloodiedWater', rarity: 'uncommon' },
            { name: 'Willow Wreath', image: 'willowWreath', rarity: 'rare' },
            { name: 'Swamp Orchid Necklet', image: 'swampOrchidNecklet', rarity: 'rare' },
            { name: 'Dried Cicada', image: 'driedCicada', rarity: 'rare' },
            { name: 'Cracked Turtle Egg', image: 'crackedTurtleEgg', rarity: 'rare' },
            { name: 'Bloodied Mud', image: 'bloodiedMud', rarity: 'rare' },
            { name: 'Scarred Hand', image: 'scarredHand', rarity: 'veryrare' },
            { name: 'Rusty Shackles', image: 'rustyShackles', rarity: 'veryrare' },
            { name: 'Granma\'s Heart', image: 'granmasHeart', rarity: 'veryrare' },
            { name: 'Disfigured Ear', image: 'disfiguredEar', rarity: 'veryrare' },
            { name: 'Waterlogged Shoe', image: 'waterloggedShoe', rarity: 'ultra' },
            { name: 'Mint Rag', image: 'mintRag', rarity: 'ultra' }
        ]
    },
    'hillbilly': {
        image: 'chainsaw',
        addons: [
            { name: 'Vegetable Oil', image: 'vegetableOil', rarity: 'common' },
            { name: 'Spark Plug', image: 'sparkPlug', rarity: 'common' },
            { name: 'Chainsaw File', image: 'chainsawFile', rarity: 'common' },
            { name: 'Spiked Boots', image: 'spikedBoots', rarity: 'uncommon' },
            { name: 'Speed Limiter', image: 'speedLimiter', rarity: 'uncommon' },
            { name: 'Shop Lubricant', image: 'shopLubricant', rarity: 'uncommon' },
            { name: 'Primer Bulb', image: 'primerBulb', rarity: 'uncommon' },
            { name: 'Long Guide Bar', image: 'longGuideBar', rarity: 'uncommon' },
            { name: 'Homemade Muffler', image: 'homemadeMuffler', rarity: 'uncommon' },
            { name: 'Grisly Chains', image: 'chainsGrisly', rarity: 'uncommon' },
            { name: 'Depth Gauge Rake', image: 'depthGaugeRake', rarity: 'uncommon' },
            { name: 'Death Engravings', image: 'deathEngravings', rarity: 'uncommon' },
            { name: 'The Thompson\'s Mix', image: 'theThompsonsMix', rarity: 'rare' },
            { name: 'Rusted Chains', image: 'chainsRusted', rarity: 'rare' },
            { name: 'Light Chassis', image: 'lightChassis', rarity: 'rare' },
            { name: 'Doom Engravings', image: 'doomEngravings', rarity: 'rare' },
            { name: 'Carburettor Tuning Guide', image: 'carburetorTuningGuide', rarity: 'rare' },
            { name: 'Thompson\'s Moonshine', image: 'thompsonsMoonshine', rarity: 'veryrare' },
            { name: 'Begrimed Chains', image: 'chainsBloody2', rarity: 'veryrare' }
        ]
    },
    'huntress': {
        image: 'huntingHatchets',
        addons: [
            { name: 'Coarse Stone', image: 'coarseStone', rarity: 'common' },
            { name: 'Berus Toxin', image: 'berusToxin', rarity: 'common' },
            { name: 'Bandaged Haft', image: 'bandagedHaft', rarity: 'common' },
            { name: 'Amanita Toxin', image: 'amanitaToxin', rarity: 'common' },
            { name: 'Yew Seed Brew', image: 'yewSeedBrew', rarity: 'uncommon' },
            { name: 'Shiny Pin', image: 'shinyPin', rarity: 'uncommon' },
            { name: 'Oak Haft', image: 'oakHaft', rarity: 'uncommon' },
            { name: 'Manna Grass Braid', image: 'mannaGrassBraid', rarity: 'uncommon' },
            { name: 'Leather Loop', image: 'leatherLoop', rarity: 'uncommon' },
            { name: 'Fine Stone', image: 'fineStone', rarity: 'uncommon' },
            { name: 'Deerskin Gloves', image: 'deerskinGloves', rarity: 'uncommon' },
            { name: 'Yew Seed Concoction', image: 'yewSeedConcoction', rarity: 'rare' },
            { name: 'Venomous Concoction', image: 'venomousConcoction', rarity: 'rare' },
            { name: 'Rusty Head', image: 'rustyHead', rarity: 'rare' },
            { name: 'Pungent Phial', image: 'pungentFiale', rarity: 'rare' },
            { name: 'Flower Babushka', image: 'flowerBabushka', rarity: 'rare' },
            { name: 'Infantry Belt', image: 'infantryBelt', rarity: 'veryrare' },
            { name: 'Glowing Concoction', image: 'glowingConcoction', rarity: 'veryrare' },
            { name: 'Begrimed Head', image: 'begrimedHead', rarity: 'veryrare' },
            { name: 'Iridescent Head', image: 'iridescentHead', rarity: 'ultra' }
        ]
    },
    'leatherface': {
        image: 'bubbasChainsaw',
        addons: [
            { name: 'Vegetable Oil', image: 'vegetableOil', rarity: 'common' },
            { name: 'Spark Plug', image: 'sparkPlug', rarity: 'common' },
            { name: 'Chainsaw File', image: 'chainsawFile', rarity: 'common' },
            { name: 'Speed Limiter', image: 'speedLimiter', rarity: 'uncommon' },
            { name: 'Shop Lubricant', image: 'shopLubricant', rarity: 'uncommon' },
            { name: 'Primer Bulb', image: 'primerBulb', rarity: 'uncommon' },
            { name: 'Long Guide Bar', image: 'longGuideBar', rarity: 'uncommon' },
            { name: 'Knife Scratches', image: 'knifeScratches', rarity: 'uncommon' },
            { name: 'Homemade Muffler', image: 'homemadeMuffler', rarity: 'uncommon' },
            { name: 'Grisly Chains', image: 'chainsGrisly', rarity: 'uncommon' },
            { name: 'Depth Gauge Rake', image: 'depthGaugeRake', rarity: 'uncommon' },
            { name: 'Chilli', image: 'chili', rarity: 'uncommon' },
            { name: 'The Grease', image: 'theGrease', rarity: 'rare' },
            { name: 'The Beast\'s Marks', image: 'theBeastsMark', rarity: 'rare' },
            { name: 'Rusted Chains', image: 'chainsRusted', rarity: 'rare' },
            { name: 'Light Chassis', image: 'lightChassis', rarity: 'rare' },
            { name: 'Carburettor Tuning Guide', image: 'carburetorTuningGuide', rarity: 'rare' },
            { name: 'Begrimed Chains', image: 'chainsBloody2', rarity: 'ultra' },
            { name: 'Award-winning Chilli', image: 'awardwinningChili', rarity: 'ultra' }
        ]
    },
    'legion': {
        image: 'feralFrenzy',
        addons: [
            { name: 'Smiley Face Pin', image: 'smileyFaceButton', rarity: 'common' },
            { name: 'Scratched Ruler', image: 'scratchedRuler', rarity: 'common' },
            { name: 'Mischief List', image: 'mischiefList', rarity: 'common' },
            { name: 'Friendship Bracelet', image: 'friendshipBracelet', rarity: 'common' },
            { name: 'Never-Sleep Pills', image: 'neverSleepPills', rarity: 'uncommon' },
            { name: 'Mural Sketch', image: 'muralSketch', rarity: 'uncommon' },
            { name: 'Julie\'s Mix Tape', image: 'juliesMixtape', rarity: 'uncommon' },
            { name: 'Etched Ruler', image: 'etchedRuler', rarity: 'uncommon' },
            { name: 'Defaced Smiley Pin', image: 'defacedSmileyButton', rarity: 'uncommon' },
            { name: 'The Legion Pin', image: 'theLegionButton', rarity: 'rare' },
            { name: 'Susie\'s Mix Tape', image: 'suziesMixtape', rarity: 'rare' },
            { name: 'Stolen Sketch Book', image: 'stolenSketchbook', rarity: 'rare' },
            { name: 'Nasty Blade', image: 'nastyBlade', rarity: 'rare' },
            { name: 'Joey\'s Mix Tape', image: 'joeysMixtape', rarity: 'rare' },
            { name: 'Stab Wounds Study', image: 'stabWoundsStudy', rarity: 'veryrare' },
            { name: 'Frank\'s Mix Tape', image: 'franksMixtape', rarity: 'veryrare' },
            { name: 'Filthy Blade', image: 'filthyBlade', rarity: 'veryrare' },
            { name: 'Cold Dirt', image: 'coldDirt', rarity: 'veryrare' },
            { name: 'Iridescent Button', image: 'iridescentButton', rarity: 'ultra' },
            { name: 'Fuming Mix Tape', image: 'fumingMixtape', rarity: 'ultra' }
        ]
    },
    'myers': {
        image: 'stalker3',
        addons: [
            { name: 'Tacky Earrings', image: 'tackyEarrings', rarity: 'common' },
            { name: 'Boyfriend\'s Memo', image: 'boyfriendsMemo', rarity: 'common' },
            { name: 'Blond Hair', image: 'blondeHair', rarity: 'common' },
            { name: 'Reflective Fragment', image: 'reflectiveFragment', rarity: 'uncommon' },
            { name: 'Memorial Flower', image: 'memorialFlower', rarity: 'uncommon' },
            { name: 'Jewelry', image: 'jewelry', rarity: 'uncommon' },
            { name: 'Hair Brush', image: 'hairBrush', rarity: 'uncommon' },
            { name: 'Glass Fragment', image: 'glassFragment', rarity: 'uncommon' },
            { name: 'Dead Rabbit', image: 'deadRabbit', rarity: 'uncommon' },
            { name: 'Mirror Shard', image: 'mirrorShard', rarity: 'rare' },
            { name: 'Judith\'s Journal', image: 'judithsJournal', rarity: 'rare' },
            { name: 'Jewelry Box', image: 'jewelryBox', rarity: 'rare' },
            { name: 'J. Myers Memorial', image: 'jMyersMemorial', rarity: 'rare' },
            { name: 'Hair Bow', image: 'hairBow', rarity: 'rare' },
            { name: 'Vanity Mirror', image: 'vanityMirror', rarity: 'veryrare' },
            { name: 'Tombstone Piece', image: 'tombstonePiece', rarity: 'veryrare' },
            { name: 'Tombstone Piece', image: 'scratchedMirror', rarity: 'veryrare' },
            { name: 'Lock Of Hair', image: 'lockOfHair', rarity: 'veryrare' },
            { name: 'Judith\'s Tombstone', image: 'judithsTombstone', rarity: 'ultra' },
            { name: 'Fragrant Tuft Of Hair', image: 'tuftOfHair', rarity: 'ultra' }
        ]
    },
    'nurse': {
        image: 'breath',
        addons: [
            { name: 'Wooden Horse', image: 'woodenHorse', rarity: 'common' },
            { name: 'White Nit Comb', image: 'whiteNitComb', rarity: 'common' },
            { name: 'Torn Bookmark', image: 'tornBookmark', rarity: 'common' },
            { name: 'Metal Spoon', image: 'metalSpoon', rarity: 'common' },
            { name: 'Matchbox', image: 'matchBox', rarity: 'common' },
            { name: 'Bad Man Keepsake', image: 'badManKeepsake', rarity: 'common' },
            { name: 'Pocket Watch', image: 'pocketWatch', rarity: 'uncommon' },
            { name: 'Dull Bracelet', image: 'dullBracelet', rarity: 'uncommon' },
            { name: 'Dark Cincture', image: 'darkCincture', rarity: 'uncommon' },
            { name: 'Catatonic Boy\'s Treasure', image: 'catatonicTreasure', rarity: 'uncommon' },
            { name: 'Spasmodic Breath', image: 'spasmodicBreath', rarity: 'rare' },
            { name: 'Heavy Panting', image: 'heavyPanting', rarity: 'rare' },
            { name: 'Fragile Wheeze', image: 'fragileWheeze', rarity: 'rare' },
            { name: 'Ataxic Respiration', image: 'ataxicRespiration', rarity: 'rare' },
            { name: 'Anxious Gasp', image: 'anxiousGasp', rarity: 'rare' },
            { name: 'Plaid Flannel', image: 'plaidFlannel', rarity: 'veryrare' },
            { name: 'Kavanagh\'s Last Breath', image: 'kavanaghsLastBreath', rarity: 'veryrare' },
            { name: 'Jenner\'s Last Breath', image: 'jennersLastBreath', rarity: 'veryrare' },
            { name: 'Campbell\'s Last Breath', image: 'campbellsLastBreath', rarity: 'veryrare' },
            { name: '"Bad Man\'s" Last Breath', image: 'badMansLastBreath', rarity: 'veryrare' }
        ]
    },
    'pig': {
        image: 'reverseBearTrap',
        addons: [
            { name: 'Workshop Grease', image: 'workshopGrease', rarity: 'common' },
            { name: 'Shattered Syringe', image: 'shatteredSyringe', rarity: 'common' },
            { name: 'John\'s Medical File', image: 'johnsMedicalFile', rarity: 'common' },
            { name: 'Combat Straps', image: 'combatStraps', rarity: 'common' },
            { name: 'Video Tape', image: 'videoTape', rarity: 'uncommon' },
            { name: 'Utility Blades', image: 'utilityBlades', rarity: 'uncommon' },
            { name: 'Razor Wires', image: 'razerWire', rarity: 'uncommon' },
            { name: 'Last Will', image: 'lastWill', rarity: 'uncommon' },
            { name: 'Face Mask', image: 'faceMask', rarity: 'uncommon' },
            { name: 'Slow-Release Toxin', image: 'slowReleaseToxin', rarity: 'rare' },
            { name: 'Rusty Attachments', image: 'rustyAttachments', rarity: 'rare' },
            { name: 'Jigsaw\'s Annotated Plan', image: 'jigsawsAnnotatedPlan', rarity: 'rare' },
            { name: 'Interlocking Razor', image: 'interlockingRazor', rarity: 'rare' },
            { name: 'Bag Of Gears', image: 'bagOfGears', rarity: 'rare' },
            { name: 'Tampered Timer', image: 'tamperedTimer', rarity: 'veryrare' },
            { name: 'Jigsaw\'s Sketch', image: 'jigsawsSketch', rarity: 'veryrare' },
            { name: 'Crate Of Gears', image: 'crateOfGears', rarity: 'veryrare' },
            { name: 'Amanda\'s Secret', image: 'amandasSecret', rarity: 'veryrare' },
            { name: 'Rules Set No.2', image: 'rulesSetN2', rarity: 'ultra' },
            { name: 'Amanda\'s Letter', image: 'amandasLetter', rarity: 'ultra' }
        ]
    },
    'spirit': {
        image: 'yamaokasHaunting',
        addons: [
            { name: 'Zori', image: 'zori', rarity: 'common' },
            { name: 'Shiawase Amulet', image: 'ShiawaseAmulet', rarity: 'common' },
            { name: 'Origami Crane', image: 'origamiCrane', rarity: 'common' },
            { name: 'Gifted Bamboo Comb', image: 'giftedBambooComb', rarity: 'common' },
            { name: 'White Hair Ribbon', image: 'whiteHairRibbon', rarity: 'uncommon' },
            { name: 'Rin\'s Broken Watch', image: 'rinsBrokenWatch', rarity: 'uncommon' },
            { name: 'Muddy Sports Day Cap', image: 'muddySportCap', rarity: 'uncommon' },
            { name: 'Kaiun Talisman', image: 'kaiunTalisman', rarity: 'uncommon' },
            { name: 'Juniper Bonsai', image: 'juniperBonzai', rarity: 'uncommon' },
            { name: 'Rusty Flute', image: 'rustyFlute', rarity: 'rare' },
            { name: 'Katsumori Talisman', image: 'katsumoriTalisman', rarity: 'rare' },
            { name: 'Katana Tsuba', image: 'katanaTsuba', rarity: 'rare' },
            { name: 'Dirty Uwabaki', image: 'dirtyUwabaki', rarity: 'rare' },
            { name: 'Bloody Hair Brooch', image: 'bloodyHairBroochi', rarity: 'rare' },
            { name: 'Yakuyoke Amulet', image: 'yakuyokeAmulet', rarity: 'veryrare' },
            { name: 'Wakizashi Saya', image: 'wakizashiSaya', rarity: 'veryrare' },
            { name: 'Prayer Beads Bracelet', image: 'prayersBeads', rarity: 'veryrare' },
            { name: 'Dried Cherry Blossom', image: 'driedCherryBlossom', rarity: 'veryrare' },
            { name: 'Mother-Daughter Ring', image: 'motherDaughterRing', rarity: 'ultra' },
            { name: 'Father\'s Glasses', image: 'fathersGlasses', rarity: 'ultra' }
        ]
    },
    'trapper': {
        image: 'trap',
        addons: [
            { name: 'Trapper Sack', image: 'trapperSack', rarity: 'common' },
            { name: 'Trapper Gloves', image: 'trapperGloves', rarity: 'common' },
            { name: 'Strong Coil Spring', image: 'coilSpring', rarity: 'common' },
            { name: 'Padded Jaws', image: 'paddedJaws', rarity: 'common' },
            { name: 'Trapper Bag', image: 'trapperBag', rarity: 'uncommon' },
            { name: 'Trap Setters', image: 'tapSetters', rarity: 'uncommon' },
            { name: 'Serrated Jaws', image: 'serratedJaws', rarity: 'uncommon' },
            { name: 'Logwood Dye', image: 'logwoodDye', rarity: 'uncommon' },
            { name: '4-Coil Spring Kit', image: 'coilsKit4', rarity: 'uncommon' },
            { name: 'Wax Brick', image: 'waxBrick', rarity: 'rare' },
            { name: 'Tar Bottle', image: 'tarBottle', rarity: 'rare' },
            { name: 'Setting Tools', image: 'settingTools', rarity: 'rare' },
            { name: 'Secondary Coil', image: 'secondaryCoil', rarity: 'rare' },
            { name: 'Rusted Jaws', image: 'rustedJaws', rarity: 'rare' },
            { name: 'Stitched Bag', image: 'stichedBag', rarity: 'veryrare' },
            { name: 'Oily Coil', image: 'oilyCoil', rarity: 'veryrare' },
            { name: 'Honing Stone', image: 'honingStone', rarity: 'veryrare' },
            { name: 'Fastening Tools', image: 'fasteningTools', rarity: 'veryrare' },
            { name: 'Iridescent Stone', image: 'diamondStone', rarity: 'ultra' },
            { name: 'Bloody Coil', image: 'bloodyCoil', rarity: 'ultra' }
        ]
    },
    'wraith': {
        image: 'bell',
        addons: [
            { name: '"The Serpent" - Soot', image: 'sootTheSerpent', rarity: 'common' },
            { name: '"The Hound" - Soot', image: 'sootTheHound', rarity: 'common' },
            { name: '"The Ghost" - Soot', image: 'sootTheGhost', rarity: 'common' },
            { name: '"The Beast" - Soot', image: 'sootTheBeast', rarity: 'common' },
            { name: 'Bone Clapper', image: 'boneClapper', rarity: 'uncommon' },
            { name: '"Blink" - Mud', image: 'mudBlink', rarity: 'uncommon' },
            { name: '"Windstorm" - Mud', image: 'mudWindstorm', rarity: 'uncommon' },
            { name: '"Swift Hunt" - Mud', image: 'mudSwiftHunt', rarity: 'uncommon' },
            { name: '"Blind Warrior" - Mud', image: 'mudBaikraKaeug', rarity: 'uncommon' },
            { name: '"Windstorm" - White', image: 'whiteWindstorm', rarity: 'rare' },
            { name: '"Swift Hunt" - White', image: 'whiteKuntinTakkho', rarity: 'rare' },
            { name: '"Shadow Dance" - White', image: 'whiteBlink', rarity: 'rare' },
            { name: '"Blink" - White', image: 'whiteShadowDance', rarity: 'rare' },
            { name: '"Blind Warrior" - White', image: 'whiteBlindWarrior', rarity: 'rare' },
            { name: '"Windstorm" - Blood', image: 'bloodWindstorm', rarity: 'veryrare' },
            { name: '"Swift Hunt" - Blood', image: 'bloodSwiftHunt', rarity: 'veryrare' },
            { name: '"Shadow Dance" - Blood', image: 'bloodShadowDance', rarity: 'veryrare' },
            { name: '"All Seeing" - Blood', image: 'bloodKraFabai', rarity: 'veryrare' },
            { name: 'Coxcombed Clapper', image: 'coxcombedClapper', rarity: 'ultra' },
            { name: '"All Seeing" - Spirit', image: 'spiritAllSeeing', rarity: 'ultra' }
        ]
    },
    'plague': {
        image: 'vilePurge',
        addons: [
            {name: 'Prayer Tablet Fragment', image: 'prayerTabletFragment', rarity: 'common'},
            {name: 'Olibanum Incense', image: 'olibanumIncense', rarity: 'common'},
            {name: 'Limestone Seal', image: 'limestoneSeal', rarity: 'common'},
            {name: 'Healing Salve', image: 'healingSalve', rarity: 'common'},
            {name: 'Prophylactic Amulet', image: 'prophylacticAmulet', rarity: 'uncommon'},
            {name: 'Potent Tincture', image: 'potentTincture', rarity: 'uncommon'},
            {name: 'Haematite Seal', image: 'hematiteSeal', rarity: 'uncommon'},
            {name: 'Emetic Potion', image: 'emeticPotion', rarity: 'uncommon'},
            {name: 'Blessed Apple', image: 'prayerApple', rarity: 'uncommon'},
            {name: 'Rubbing Oil', image: 'rubbingOil', rarity: 'rare'},
            {name: 'Infected Emetic', image: 'infectedEmetic', rarity: 'rare'},
            {name: 'Incensed Ointment', image: 'incensedOintment', rarity: 'rare'},
            {name: 'Exorcism Amulet', image: 'exorcismAmulet', rarity: 'rare'},
            {name: 'Ashen Apple', image: 'ashenApple', rarity: 'rare'},
            {name: 'Worship Tablet', image: 'worshipTablet', rarity: 'veryrare'},
            {name: 'Vile Emetic', image: 'vileEmetic', rarity: 'veryrare'},
            {name: 'Severed Toe', image: 'severedToe', rarity: 'veryrare'},
            {name: 'Devotee\'s Amulet', image: 'devoteesAmulet', rarity: 'veryrare'},
            {name: 'Iridescent Seal', image: 'IridescentSeal', rarity: 'ultra'},
            {name: 'Black Incense', image: 'blackIncense', rarity: 'ultra'}
        ]
    },
    'ghostface': {
        image: 'ghostPower',
        addons: [
            { name: '"Philly"', image: 'philly', rarity: 'common' },
            { name: 'Walleyes Matchbook', image: 'walleyesMatchbook', rarity: 'common' },
            { name: 'Headlines Cut-outs', image: 'headlinesCutouts', rarity: 'common' },
            { name: 'Cheap Cologne', image: 'cheapCologne', rarity: 'common' },
            { name: 'Telephoto Lens', image: 'telephotoLens', rarity: 'uncommon' },
            { name: 'Reusable Cinch Strap', image: 'reusuableCinchStraps', rarity: 'uncommon' },
            { name: 'Olsen\'s Journal', image: 'olsensJournal', rarity: 'uncommon' },
            { name: 'Olsen\'s Address Book', image: 'olsensAddressBook', rarity: 'uncommon' },
            { name: 'Marked Map', image: 'markedMap', rarity: 'uncommon' },
            { name: 'Olsen\'s Wallet', image: 'olsensWallet', rarity: 'rare' },
            { name: 'Leather Knife Sheath', image: 'leatherKnifeSheath', rarity: 'rare' },
            { name: 'Lasting Perfume', image: 'lastingPerfume', rarity: 'rare' },
            { name: 'Knife Belt Clip', image: 'knifeBeltClip', rarity: 'rare' },
            { name: 'Chewed Pen', image: 'chewedPen', rarity: 'rare' },
            { name: 'Victim\'s Detailed Routine', image: 'victimsDetailedRoutine', rarity: 'veryrare' },
            { name: 'Night Vision Monocular', image: 'nightvisionMoncular', rarity: 'veryrare' },
            { name: 'Drop-Leg Knife Sheath', image: 'dropLegKnifeSheath', rarity: 'veryrare' },
            { name: 'Driver\'s License', image: 'driversLicense', rarity: 'veryrare' },
            { name: '"Ghost Face Caught on Tape"', image: 'caughtOnTape', rarity: 'ultra' },
            { name: 'Outdoor Security Camera', image: 'outdoorSecurityCamera', rarity: 'ultra' }
        ]
    },
    'demogorgon': {
        image: 'ofTheAbyss',
        addons: [
            { name: 'Rotten Pumpkin', image: 'rottenPumpkin', rarity: 'common' },
            { name: 'Black Heart', image: 'blackHeart', rarity: 'common' },
            { name: 'Rat Liver', image: 'ratLiver', rarity: 'common' },
            { name: 'Rat Tail', image: 'ratTail', rarity: 'common' },
            { name: 'Sticky Lining', image: 'stickyLining', rarity: 'uncommon' },
            { name: 'Viscous Webbing', image: 'viscousWebbing', rarity: 'uncommon' },
            { name: 'Rotten Green Tripe', image: 'rottenGreenTripe', rarity: 'uncommon' },
            { name: 'Mew\'s Guts', image: 'mewsGuts', rarity: 'uncommon' },
            { name: 'Barb\'s Glasses', image: 'barbsGlasses', rarity: 'uncommon' },
            { name: 'Eleven\'s Soda', image: 'elevensSoda', rarity: 'rare' },
            { name: 'Thorny Vines', image: 'thornyVines', rarity: 'rare' },
            { name: 'Brass Case Lighter', image: 'brassCaseLighter', rarity: 'rare' },
            { name: 'Violet Waxcap', image: 'violetWaxcap', rarity: 'rare' },
            { name: 'Deer Lung', image: 'deerLung', rarity: 'rare' },
            { name: 'Lifeguard Whistle', image: 'lifeguardWhistle', rarity: 'veryrare' },
            { name: 'Vermilion Webcap', image: 'vermillionWebcap', rarity: 'veryrare' },
            { name: 'Upside Down Resin', image: 'upsidedownResin', rarity: 'veryrare' },
            { name: 'Unknown Egg', image: 'unknownEgg', rarity: 'veryrare' },
            { name: 'Leprose Lichen', image: 'leproseLichen', rarity: 'ultra' },
            { name: 'Red Moss', image: 'redMoss', rarity: 'ultra' }
        ]
    },
    'oni' : {
        image: 'yamaokasWrath',
        addons: [
            { name: 'Yakuyoke Talisman', image: 'paperLantern', rarity: 'common' },
            { name: 'Rotting Rope', image: 'rottingRope', rarity: 'common' },
            { name: 'Cracked Sakazuki', image: 'crackedSakazuki', rarity: 'common' },
            { name: 'Blackened Toenail', image: 'blackenedToenail', rarity: 'common' },
            { name: 'Polished Maedate', image: 'polishedMaedate', rarity: 'uncommon' },
            { name: 'Ink Lion', image: 'inkLion', rarity: 'uncommon' },
            { name: 'Chipped Saihai', image: 'chippedSaihai', rarity: 'uncommon' },
            { name: 'Child\'s Wooden Sword', image: 'childsWoodenSword', rarity: 'uncommon' },
            { name: 'Bloody Sash', image: 'bloodySash', rarity: 'uncommon' },
            { name: 'Yamaoka Sashimono', image: 'yamaokaSashimono', rarity: 'rare' },
            { name: 'Wooden Oni Mask', image: 'woodenOniMask', rarity: 'rare' },
            { name: 'Shattered Wakizashi', image: 'shatteredWakizashi', rarity: 'rare' },
            { name: 'Scalped Topknot', image: 'scalpedTopknot', rarity: 'rare' },
            { name: 'Kanai-Anzen Talisman', image: 'kanaianzenTalisman', rarity: 'rare' },
            { name: 'Tear Soaked Tenugui', image: 'tearSoakedTenugui', rarity: 'veryrare' },
            { name: 'Splintered Hull', image: 'splinteredHull', rarity: 'veryrare' },
            { name: 'Lion Fang', image: 'lionFang', rarity: 'veryrare' },
            { name: 'Akito\'s Crutch', image: 'akitosCrutch', rarity: 'veryrare' },
            { name: 'Renjiro\'s Bloody Glove', image: 'IridescentFamilyCrest', rarity: 'ultra' },
            { name: 'Iridescent Family Crest', image: 'renirosBloodyGlove', rarity: 'ultra' },
        ]
    },
    'deathslinger' : {
        image: 'redeemer',
        addons: [
            { name: 'Spit Polish Rag', image: 'spitPolishRag', rarity: 'common' },
            { name: 'Snake Oil', image: 'snakeOil', rarity: 'common' },
            { name: 'Rickety Chain', image: 'ricketyChain', rarity: 'common' },
            { name: 'Modified Ammo Belt', image: 'modifiedAmmoBelt', rarity: 'common' },
            { name: 'Rusted Spike', image: 'rustedSpike', rarity: 'uncommon' },
            { name: 'Poison Oak Leaves', image: 'poisonOakLeaves', rarity: 'uncommon' },
            { name: 'Marshal\'s Badge', image: 'marshalsBadge', rarity: 'uncommon' },
            { name: 'Jaw Smasher', image: 'jawSmasher', rarity: 'uncommon' },
            { name: 'Chewing Tobacco', image: 'chewingTobacco', rarity: 'uncommon' },
            { name: 'Warden\'s Keys', image: 'wardensKeys', rarity: 'rare' },
            { name: 'Wanted Poster', image: 'wantedPoster', rarity: 'rare' },
            { name: 'Tin Oil Can', image: 'tinOilCan', rarity: 'rare' },
            { name: 'Honey Locust Thorn', image: 'honeyLocustThorns', rarity: 'rare' },
            { name: 'Bayshore\'s Gold Tooth', image: 'bayshoresGoldTooth', rarity: 'rare' },
            { name: 'Barbed Wire', image: 'barbedWire', rarity: 'veryrare' },
            { name: 'Bayshore\'s Cigar', image: 'bayshoresCigar', rarity: 'veryrare' },
            { name: 'Gold Creek Whiskey', image: 'clearCreekWhiskey', rarity: 'veryrare' },
            { name: 'Prison Chain', image: 'prisonChain', rarity: 'veryrare' },
            { name: 'Hellshire Iron', image: 'hellshireIron', rarity: 'ultra' },
            { name: 'Iridescent Coin', image: 'iridescentCoin', rarity: 'ultra' }
        ]
    },
    'executioner' : {
        image: 'ritesOfJudgement',
        addons: [
            { name: 'Black Strap', image: 'blackStrap', rarity: 'common' },
            { name: 'Copper Ring', image: 'copperRing', rarity: 'common' },
            { name: 'Dead Butterfly', image: 'deadButterfly', rarity: 'common' },
            { name: 'Lead Ring', image: 'leadRing', rarity: 'common' },
            { name: 'Cinderella Music Box', image: 'cinderellaMusicBox', rarity: 'uncommon' },
            { name: 'Forgotten Videotape', image: 'forgottenVideoTape', rarity: 'uncommon' },
            { name: 'Leopard-Print Fabric', image: 'leopardPrintFabric', rarity: 'uncommon' },
            { name: 'Wax Doll', image: 'waxDoll', rarity: 'uncommon' },
            { name: 'Spearhead', image: 'spearhead', rarity: 'uncommon' },
            { name: 'Burning Man Painting', image: 'burningManPainting', rarity: 'rare' },
            { name: 'Mannequin Foot', image: 'mannequinFoot', rarity: 'rare' },
            { name: 'Misty Day, Remains of Judgement', image: 'mistyDay', rarity: 'rare' },
            { name: 'Tablet of the Oppressor', image: 'tabletOfTheOppressor', rarity: 'rare' },
            { name: 'Valtiel Sect Photograph', image: 'valtielSectPhotograph', rarity: 'rare' },
            { name: 'Crimson Ceremony Book', image: 'crimsonCeremonyBook', rarity: 'veryrare' },
            { name: 'Lost Memories Book', image: 'lostMemoriesBook', rarity: 'veryrare' },
            { name: 'Rust-Coloured Egg', image: 'rustColoredEgg', rarity: 'veryrare' },
            { name: 'Scarlet Egg', image: 'scarletEgg', rarity: 'veryrare' },
            { name: 'Iridescent Seal of Metatron', image: 'iridescentSeal', rarity: 'ultra' },
            { name: 'Obsidian Goblet', image: 'obsidianGoblet', rarity: 'ultra' }
        ]
    },
    'blight' : {
        image: 'K21',
        addons: [
            { name: 'Placebo Tablet', image: 'placeboTablet', rarity: 'common' },
            { name: 'Foxglove', image: 'foxglove', rarity: 'common' },
            { name: 'Compound Seven', image: 'compoundSeven', rarity: 'common' },
            { name: 'Chipped Monocle', image: 'chippedMonocle', rarity: 'common' },
            { name: 'Shredded Notes', image: 'shreddedNotes', rarity: 'uncommon' },
            { name: 'Pustula Dust', image: 'pustulaDust', rarity: 'uncommon' },
            { name: 'Plague Bile', image: 'plagueBile', rarity: 'uncommon' },
            { name: 'Canker Thorn', image: 'cankerThorn', rarity: 'uncommon' },
            { name: 'Blighted Rat', image: 'blightedRat', rarity: 'uncommon' },
            { name: 'Umbra Salts', image: 'umbraSalts', rarity: 'rare' },
            { name: 'Rose Tonic', image: 'roseTonic', rarity: 'rare' },
            { name: 'Compound Twenty-One', image: 'compoundTwentyOne', rarity: 'rare' },
            { name: 'Blighted Crow', image: 'blightedCrow', rarity: 'rare' },
            { name: 'Adrenaline Vial', image: 'adrenalineVial', rarity: 'rare' },
            { name: 'Vigo\'s Journal', image: 'vigosJournal', rarity: 'veryrare' },
            { name: 'Summoning Stone', image: 'summoningStone', rarity: 'veryrare' },
            { name: 'Soul Chemical', image: 'soulChemical', rarity: 'veryrare' },
            { name: 'Alchemist\'s Ring', image: 'alchemistsRing', rarity: 'veryrare' },
            { name: 'Iridescent Blight Tag', image: 'iridescentBlightTag', rarity: 'ultra' },
            { name: 'Compound Thirty-Three', image: 'compoundThirtyThree', rarity: 'ultra' }
        ]
    },
    'twins' : {
        image: 'bloodBond',
        addons: [
            { name: 'Toy Sword', image: 'toySword', rarity: 'common' },
            { name: 'Tiny Fingernail', image: 'tinyFingernail', rarity: 'common' },
            { name: 'Soured Milk', image: 'souredMilk', rarity: 'common' },
            { name: 'Cat Figurine', image: 'catFigurine', rarity: 'common' },
            { name: 'Madeleine\'s Glove', image: 'madeleinesGlove', rarity: 'uncommon' },
            { name: 'Ceremonial Candelabrum', image: 'ceremonialCandelabrum', rarity: 'uncommon' },
            { name: 'Cat\'s Eye', image: 'catsEye', rarity: 'uncommon' },
            { name: 'Bloody Black Hood', image: 'bloodiedBlackHood', rarity: 'uncommon' },
            { name: 'Baby Teeth', image: 'babyTeeth', rarity: 'uncommon' },
            { name: 'Weighty Rattle', image: 'weightyRattle', rarity: 'rare' },
            { name: 'Stale Biscuit', image: 'staleBiscuit', rarity: 'rare' },
            { name: 'Sewer Sludge', image: 'sewerSludge', rarity: 'rare' },
            { name: 'Rusted Needle', image: 'rustedNeedle', rarity: 'rare' },
            { name: 'Madeleine\'s Scarf', image: 'madeleinesScarf', rarity: 'rare' },
            { name: 'Victor\'s Soldier', image: 'victorsSoldier', rarity: 'veryrare' },
            { name: 'Spinning Top', image: 'spinningTop', rarity: 'veryrare' },
            { name: 'Forest Stew', image: 'forestStew', rarity: 'veryrare' },
            { name: 'Drop of Perfume', image: 'dropOfPerfume', rarity: 'veryrare' },
            { name: 'Silencing Cloth', image: 'silencingCloth', rarity: 'ultra' },
            { name: 'Iridescent Pendant', image: 'iridescentPendant', rarity: 'ultra' }
        ]
    },
    'trickster' : {
        image: 'showstopper',
        addons: [
            { name: 'Trick Pouch', image: 'trickPouch', rarity: 'common' },
            { name: 'Memento Blades', image: 'mementoBlades', rarity: 'common' },
            { name: 'Killing Part Chords', image: 'killingPartChords', rarity: 'common' },
            { name: 'Inferno Wires', image: 'infernoWires', rarity: 'common' },
            { name: 'Tequila Moonrock', image: 'tequilaMoonrock', rarity: 'uncommon' },
            { name: 'On Target Single', image: 'onTargetSingle', rarity: 'uncommon' },
            { name: 'Lucky Blade', image: 'luckyBlade', rarity: 'uncommon' },
            { name: 'Ji-Woon\'s Autograph', image: 'jiWoonsAutograph', rarity: 'uncommon' },
            { name: 'Caged Heart Shoes', image: 'cagedHeartShoes', rarity: 'uncommon' },
            { name: 'Melodious Murder', image: 'melodiousMurder', rarity: 'rare' },
            { name: 'Waiting for U Watch', image: 'waitingForYouWatch', rarity: 'rare' },
            { name: 'Ripper Brace', image: 'ripperBrace', rarity: 'rare' },
            { name: 'Fizz-Spin Soda', image: 'fizz-SpinSoda', rarity: 'rare' },
            { name: 'Bloody Boa', image: 'bloodyBoa', rarity: 'rare' },
            { name: 'Trick Blades', image: 'trickBlades', rarity: 'veryrare' },
            { name: 'Edge of Revival Album', image: 'edgeOfRevivalAlbum', rarity: 'veryrare' },
            { name: 'Diamond Cufflinks', image: 'diamondCufflinks', rarity: 'veryrare' },
            { name: 'Cut Through U Single', image: 'cutThruUSingle', rarity: 'veryrare' },
            { name: 'Iridescent Photocard', image: 'iridescentPhotocard', rarity: 'ultra' },
            { name: 'Death Throes Compilation', image: 'deathThroesCompilation', rarity: 'ultra' }
           ]                 
    },
    'nemesis' : {
        image: 'TVirus',
        addons: [
            { name: 'Visitor Wristband', image: 'visitorWristband', rarity: 'common' },
            { name: 'STARS Field Combat Manual', image: 'starsFieldCombatManual', rarity: 'common' },
            { name: 'Damaged Syringe', image: 'damagedSyringe', rarity: 'common' },
            { name: 'Brian\'s Intestine', image: 'briansIntestine', rarity: 'common' },
            { name: 'Zombie Heart', image: 'zombieHeart', rarity: 'uncommon' },
            { name: 'Mikhail\'s Eye', image: 'mikhailsEye', rarity: 'uncommon' },
            { name: 'Marvin\'s Blood', image: 'marvinsBlood', rarity: 'uncommon' },
            { name: 'Adrenaline Injector', image: 'adrenalineInjector', rarity: 'uncommon' },
            { name: 'Admin Wristband', image: 'adminWristband', rarity: 'uncommon' },
            { name: 'Tyrant Gore', image: 'tyrantGore', rarity: 'rare' },
            { name: 'T-Virus Sample', image: 't-VirusSample', rarity: 'rare' },
            { name: 'Serotonin Injector', image: 'serotoninInjector', rarity: 'rare' },
            { name: 'Plant 43 Vines', image: 'plant43Vines', rarity: 'rare' },
            { name: 'Licker Tongue', image: 'lickerTongue', rarity: 'rare' },
            { name: 'NE-a Parasite', image: 'ne-AParasite', rarity: 'veryrare' },
            { name: 'Jill\'s Sandwich', image: 'jillsSandwich', rarity: 'veryrare' },
            { name: 'Depleted Ink Ribbon', image: 'depletedInkRibbin', rarity: 'veryrare' },
            { name: 'Broken Recovery Coin', image: 'brokenRecoveryCoin', rarity: 'veryrare' },
            { name: 'Shattered STARS Badge', image: 'shatteredSTARSBadge', rarity: 'ultra' },
            { name: 'Iridescent Umbrella Badge', image: 'iridescentUmbrellaBadge', rarity: 'ultra' }
        ]
    },
    'cenobite' : {
        image: 'SummonsofPain',
        addons: [
            { name: 'Leather Strip', image: 'leatherStrip', rarity: 'common' },
            { name: 'Liverly Crickets', image: 'livelyCrickets', rarity: 'common' },
            { name: 'Burning Candle', image: 'burningCandle', rarity: 'common' },
            { name: 'Bent Nail', image: 'bentNail', rarity: 'common' },
            { name: 'Wriggeling Maggots', image: 'wriggelingMaggots', rarity: 'uncommon' },
            { name: 'Spoiled Meal', image: 'spoiledMeal', rarity: 'uncommon' },
            { name: 'Skewered Rat', image: 'skeweredRat', rarity: 'uncommon' },
            { name: 'Liquified Gore', image: 'liquifiedGore', rarity: 'uncommon' },
            { name: 'Flickering Television', image: 'flickeringTelevision', rarity: 'uncommon' },
            { name: 'Torture Pillar', image: 'torturePillar', rarity: 'rare' },
            { name: 'Silence of Frank', image: 'silenceOfFrank', rarity: 'rare' },
            { name: 'Larry\'s Remains', image: 'larrysRemains', rarity: 'rare' },
            { name: 'Larry\'s Blood', image: 'larrysBlood', rarity: 'rare' },
            { name: 'Frank\'s Heart', image: 'franksHeart', rarity: 'rare' },
            { name: 'Original Pain', image: 'otiginalPain', rarity: 'veryrare' },
            { name: 'Impaling Wire', image: 'impalingWire', rarity: 'veryrare' },
            { name: 'Greasy Black Lens', image: 'greasyBlackLens', rarity: 'veryrare' },
            { name: 'Chatterer\'s Tooth', image: 'chatterersTooth', rarity: 'veryrare' },
            { name: 'Iridescent Lament Configuration', image: 'iridescentLamentConfiguration', rarity: 'ultra' },
            { name: 'Engineer\'s Fang', image: 'engineersFang', rarity: 'ultra' }
        ]
    },
    'artist' : {
        image: 'BirdsofTorment',
        addons: [
            { name: 'Vibrant Obituary', image: 'vibrantObituary', rarity: 'common' },
            { name: 'Thick Tar', image: 'thickTar', rarity: 'common' },
            { name: 'Oil Paints', image: 'oilPaints', rarity: 'common' },
            { name: 'Choclo Corn', image: 'chocloCorn', rarity: 'common' },
            { name: 'Velvet Fabric', image: 'velvetFabric', rarity: 'uncommon' },
            { name: 'Untitled Agony', image: 'untitledAgony', rarity: 'uncommon' },
            { name: 'Still Life Crow', image: 'stillLifeCrow', rarity: 'uncommon' },
            { name: 'Festering Carrion', image: 'feseteringCarrion', rarity: 'uncommon' },
            { name: 'Automatic Drawing', image: 'automaticDrawing', rarity: 'uncommon' },
            { name: 'Thorny Nest', image: 'thornyNest', rarity: 'rare' },
            { name: 'Silver Bell', image: 'silverBell', rarity: 'veryrare' },
            { name: 'O Grief O Lover', image: 'oGriefOLover', rarity: 'rare' },
            { name: 'Darkest Ink', image: 'darkestInk', rarity: 'rare' },
            { name: 'Charcoal Stick', image: 'charcoalStick', rarity: 'rare' },
            { name: 'Severed Tongue', image: 'severedTongue', rarity: 'rare' },
            { name: 'Severed Hands', image: 'severedHands', rarity: 'veryrare' },
            { name: 'Matias\' Baby Shoes', image: 'matiasBabyShoes', rarity: 'veryrare' },
            { name: 'Ink Egg', image: 'inkEggs', rarity: 'veryrare' },
            { name: 'Iridescent Feather', image: 'iridescentFeather', rarity: 'ultra' },
            { name: 'Garden of Rot', image: 'gardenOfRot', rarity: 'ultra' }
        ]
    }
};

const SURVIVOR_ITEMS = [
    { name: 'Broken Key', image: 'brokenKey', type: 'key', rarity: 'rare' },
    { name: 'Dull Key', image: 'dullKey2', type: 'key', rarity: 'veryrare' },
    { name: 'Skeleton Key', image: 'key', type: 'key', rarity: 'ultra' },
    { name: 'Camping Aid Kit', image: 'rundownAidKit', type: 'medkit', rarity: 'common' },
    { name: 'First Aid Kit', image: 'firstAidKit', type: 'medkit', rarity: 'uncommon' },
    { name: 'Emergency Med-Kit', image: 'medkit', type: 'medkit', rarity: 'rare' },
    { name: 'Ranger Med-Kit', image: 'rangersAidKit', type: 'medkit', rarity: 'veryrare' },
    { name: 'Flashlight ', image: 'flashlight', type: 'flashlight', rarity: 'uncommon' },
    { name: 'Sport Flashlight', image: 'flashlightSport', type: 'flashlight', rarity: 'rare' },
    { name: 'Utility Flashlight', image: 'flashlightUtility', type: 'flashlight', rarity: 'veryrare' },
    { name: 'Map', image: 'map', type: 'map', rarity: 'rare' },
    { name: 'Rainbow Map', image: 'rainbowMap', type: 'map', rarity: 'ultra' },
    { name: 'Worn-Out Tools', image: 'toolboxWornOut', type: 'toolbox', rarity: 'common' },
    { name: 'Toolbox', image: 'toolbox', type: 'toolbox', rarity: 'uncommon' },
    { name: 'Mechanic\'s Toolbox', image: 'toolboxMechanics', type: 'toolbox', rarity: 'rare' },
    { name: 'Commodious Toolbox', image: 'toolboxCommodious', type: 'toolbox', rarity: 'rare' },
    { name: 'Engineer\'s Toolbox', image: 'toolboxEngineers', type: 'toolbox', rarity: 'veryrare' },
    { name: 'Alex\'s Toolbox', image: 'toolboxAlexs', type: 'toolbox', rarity: 'veryrare' }
];

const ITEMS_ADDONS =  {
    'key': [
        { name: 'Prayer Rope', image: 'prayerRope', rarity: 'common' },
        { name: 'Scratched Pearl', image: 'scratchedPearl', rarity: 'uncommon' },
        { name: 'Prayer Beads', image: 'prayerBeads', rarity: 'uncommon' },
        { name: 'Eroded Token', image: 'tokenErroded', rarity: 'uncommon' },
        { name: 'Gold Token', image: 'tokenGold', rarity: 'rare' },
        { name: 'Weaved Ring', image: 'weavedRing', rarity: 'veryrare' },
        { name: 'Milky Glass', image: 'milkyGlass', rarity: 'veryrare' },
        { name: 'Blood Amber', image: 'bloodAmber', rarity: 'veryrare' }
    ],
    'medkit': [
        { name: 'Rubber Gloves', image: 'gloves', rarity: 'common' },
        { name: 'Butterfly Tape', image: 'butterflyTape', rarity: 'common' },
        { name: 'Bandages', image: 'bandages', rarity: 'common' },
        { name: 'Sponge', image: 'sponge', rarity: 'uncommon' },
        { name: 'Self Adherent Wrap', image: 'selfAdherentWrap', rarity: 'uncommon' },
        { name: 'Needle & Thread', image: 'needAndThread', rarity: 'uncommon' },
        { name: 'Medical Scissors', image: 'scissors', rarity: 'uncommon' },
        { name: 'Gauze Roll', image: 'gauseRoll', rarity: 'uncommon' },
        { name: 'Surgical Suture', image: 'surgicalSuture', rarity: 'rare' },
        { name: 'Gel Dressings', image: 'gelDressings', rarity: 'rare' },
        { name: 'Abdominal Dressing', image: 'abdominalDressing', rarity: 'rare' },
        { name: 'Styptic Agent', image: 'stypticAgent', rarity: 'veryrare' },
        { name: 'Anti-Hemorrhagic Syringe', image: 'syringe', rarity: 'ultra' }
    ],
    'flashlight': [
        { name: 'Wide Lens', image: 'wideLens', rarity: 'common' },
        { name: 'Power Bulb', image: 'powerBulb', rarity: 'common' },
        { name: 'Leather Grip', image: 'leatherGrip', rarity: 'common' },
        { name: 'Battery', image: 'battery', rarity: 'common' },
        { name: 'Tir Optic', image: 'tirOptic', rarity: 'uncommon' },
        { name: 'Rubber Grip', image: 'rubberGrip', rarity: 'uncommon' },
        { name: 'Low Amp Filament', image: 'threadedFilament', rarity: 'uncommon' },
        { name: 'Heavy Duty Battery', image: 'heavyDutyBattery', rarity: 'uncommon' },
        { name: 'Focus Lens', image: 'focusLens', rarity: 'uncommon' },
        { name: 'Long Life Battery', image: 'longLifeBattery', rarity: 'rare' },
        { name: 'Intense Halogen', image: 'intenseHalogen', rarity: 'rare' },
        { name: 'High-End Sapphire Lens', image: 'highEndSapphireLens', rarity: 'veryrare' },
        { name: 'Odd Bulb', image: 'oddBulb', rarity: 'ultra' }
    ],
    'map': [
        { name: 'Map Addendum', image: 'mapAddendum', rarity: 'common' },
        { name: 'Yellow Wire', image: 'ropeYellow', rarity: 'uncommon' },
        { name: 'Unusual Stamp', image: 'stampUnusual', rarity: 'uncommon' },
        { name: 'Retardant Jelly', image: 'retardantJelly', rarity: 'uncommon' },
        { name: 'Red Twine', image: 'ropeRed', rarity: 'uncommon' },
        { name: 'Glass Bead', image: 'beadGlass', rarity: 'uncommon' },
        { name: 'Odd Stamp', image: 'stampOdd', rarity: 'rare' },
        { name: 'Black Silk Cord', image: 'ropeBlack', rarity: 'rare' },
        { name: 'Crystal Bead', image: 'beadCrystal', rarity: 'veryrare' }
    ],
    'toolbox': [
        { name: 'Spring Clamp', image: 'springClamp', rarity: 'common' },
        { name: 'Scraps', image: 'scraps', rarity: 'common' },
        { name: 'Clean Rag', image: 'cleanRag', rarity: 'common' },
        { name: 'Wire Spool', image: 'spoolOfWire', rarity: 'uncommon' },
        { name: 'Socket Swivels', image: 'socketSwivels', rarity: 'uncommon' },
        { name: 'Protective Gloves', image: 'protectiveGloves', rarity: 'uncommon' },
        { name: 'Instructions', image: 'instructions', rarity: 'uncommon' },
        { name: 'Grip Wrench', image: 'gripWrench', rarity: 'uncommon' },
        { name: 'Cutting Wire', image: 'cuttingWire', rarity: 'uncommon' },
        { name: 'Hacksaw', image: 'metalSaw', rarity: 'rare' },
        { name: 'Brand New Part', image: 'brandNewPart', rarity: 'ultra' },
    ]
};

const COMMON_OFFERS = [
    { name: 'Azarov\'s Key', image:'azarovsKey', type: 'common', rarity: 'rare' },
    { name: 'Charred Wedding Photograph', image:'charredWeddingPhotograph', type: 'common', rarity: 'rare' },
    { name: 'Damaged Photo', image:'damagedPhoto', type: 'common', rarity: 'rare' },
    { name: 'Granma\'s Cookbook', image:'granmasCookbook', type: 'common', rarity: 'rare' },
    { name: 'Hawkins National Laboratory', image:'hawkinsNationalLaboratory', type: 'common', rarity: 'rare' },
    { name: 'Heart Locket', image:'heartLocket', type: 'common', rarity: 'rare' },
    { name: 'Jigsaw Piece', image:'jigsawPiece', type: 'common', rarity: 'rare' },
    { name: 'MacMillan\'s Phalanx Bone', image:'macmilliansPhalanxBone', type: 'common', rarity: 'rare' },
    { name: 'Shattered Glasses', image:'shatteredGlasses', type: 'common', rarity: 'rare' },
    { name: 'Strode Realty Key', image:'strodeRealtyKey', type: 'common', rarity: 'rare' },
    { name: 'The Last Mask', image:'theLastMask', type: 'common', rarity: 'rare' },
    { name: 'The Pied Piper', image:'thePiedPiper', type: 'common', rarity: 'rare' },
    { name: 'Yamaoka Family Crest', image:'yamaokasCrest', type: 'common', rarity: 'rare' },
    { name: 'Clear Reagent', image:'clearReagent', type: 'common', rarity: 'common' },
    { name: 'Faint Reagent', image:'faintReagent', type: 'common', rarity: 'common' },
    { name: 'Hazy Reagent', image:'hazyReagent', type: 'common', rarity: 'uncommon' },
    { name: 'Murky Reagent', image:'murkyReagent', type: 'common', rarity: 'veryrare' },
    { name: 'Bloody Party Streamers', image:'bloodyPartyStreamers', type: 'common', rarity: 'rare' },
    { name: 'Dusty Noose', image:'dustyNoose', type: 'common', rarity: 'rare' },
    { name: 'Mary\'s Letter', image:'marysLetter', type: 'common', rarity: 'rare' },
    { name: 'Annotated Blueprint', image: 'annotatedBlueprint', type: 'common', rarity: 'common' },
    { name: 'Bloodied Blueprint', image: 'bloodiedBlueprint', type: 'common', rarity: 'common' },
    { name: 'Torn Blueprint', image: 'tornBlueprint', type: 'common', rarity: 'common' },
    { name: 'Vigo\'s Blueprint', image: 'vigosBlueprint', type: 'common', rarity: 'common' },
    { name: 'Sacrificial Ward', image: 'wardSacrificial', type: 'common', rarity: 'rare' }
];

const KILLER_OFFERS = $.merge([
    { name: 'Raven Wreath', image: 'ravenWreath', type: 'killer', rarity: 'common' },
    { name: 'Shrike Wreath', image: 'shrikeWreath', type: 'killer', rarity: 'common' },
    { name: 'Spotted Owl Wreath', image: 'spottedOwlWreath', type: 'killer', rarity: 'common' },
    { name: 'Tanager Wreath', image: 'tanagerWreath', type: 'killer', rarity: 'common' },
    { name: 'Devout Raven Wreath', image: 'devoutRavenWreath', type: 'killer', rarity: 'uncommon' },
    { name: 'Devout Shrike Wreath', image: 'devoutShrikeWreath', type: 'killer', rarity: 'uncommon' },
    { name: 'Devout Spotted Owl Wreath', image: 'devoutSpottedOwlWreath', type: 'killer', rarity: 'uncommon' },
    { name: 'Devout Tanager Wreath', image: 'devoutTanagerWreath', type: 'killer', rarity: 'uncommon' },
    { name: 'Hollow Shell', image: 'hollowShell', type: 'killer', rarity: 'uncommon' },
    { name: 'Survivor Pudding', image: 'survivorPudding', type: 'killer', rarity: 'uncommon' },
    { name: 'Ardent Raven Wreath', image: 'ardentRavenWreath', type: 'killer', rarity: 'rare' },
    { name: 'Ardent Shrike Wreath', image: 'ardentShrikeWreath', type: 'killer', rarity: 'rare' },
    { name: 'Ardent Spotted Owl Wreath', image: 'ardentSpottedOwlWreath', type: 'killer', rarity: 'rare' },
    { name: 'Ardent Tanager Wreath', image: 'ardentTanagerWreath', type: 'killer', rarity: 'rare' },
    { name: 'Cut Coin', image: 'cutCoin', type: 'killer', rarity: 'veryrare' },
    { name: 'Scratched Coin', image: 'scratchedCoin', type: 'killer', rarity: 'uncommon' },
    { name: 'Mouldy Oak', image: 'moldyOak', type: 'killer', rarity: 'uncommon' },
    { name: 'Rotten Oak', image: 'rottenOak', type: 'killer', rarity: 'rare' },
    { name: 'Putrid Oak', image: 'putridOak', type: 'killer', rarity: 'veryrare' },
    { name: 'Cypress Memento Mori', image: 'momentoMoriCypress', type: 'killer', rarity: 'uncommon' },
    { name: 'Ivory Memento Mori', image: 'momentoMoriIvory', type: 'killer', rarity: 'rare' },
    { name: 'Ebony Memento Mori', image: 'momentoMoriEbony', type: 'killer', rarity: 'ultra' },
    { name: 'Shroud of Separation', image: 'shroudOfSeparation', type: 'killer', rarity: 'uncommon' },
    { name: 'Black Ward', image: 'wardBlack', type: 'killer', rarity: 'veryrare' }
], COMMON_OFFERS);

const SURVIVOR_OFFERS = $.merge([
    { name: 'Bog Laurel Sachet', image: 'bogLaurelSachet', type: 'survivor', rarity: 'common' },
    { name: 'Crispleaf Amaranth Sachet', image: 'crispleafAmaranthSachet', type: 'survivor', rarity: 'common' },
    { name: 'Primrose Blossom Sachet', image: 'primroseBlossomSachet', type: 'survivor', rarity: 'common' },
    { name: 'Sweet William Sachet ', image: 'sweetWilliamSachet', type: 'survivor', rarity: 'common' },
    { name: 'Fresh Bog Laurel', image: 'freshBogLaurel', type: 'survivor', rarity: 'uncommon' },
    { name: 'Fresh Crispleaf Amaranth', image: 'freshCrispleafAmaranth', type: 'survivor', rarity: 'uncommon' },
    { name: 'Fresh Primrose Blossom', image: 'freshPrimroseBlossom', type: 'survivor', rarity: 'uncommon' },
    { name: 'Fresh Sweet William', image: 'freshSweetWilliam', type: 'survivor', rarity: 'uncommon' },
    { name: 'Escape! Cake', image: 'escapeCake', type: 'survivor', rarity: 'uncommon' },
    { name: 'Sealed Envelope', image: 'sealedEnvelope', type: 'survivor', rarity: 'uncommon' },
    { name: 'Fragrant Bog Laurel', image: 'fragrantBogLaurel', type: 'survivor', rarity: 'rare' },
    { name: 'Fragrant Crispleaf Amaranth', image: 'fragrantCrispleafAmaranth', type: 'survivor', rarity: 'rare' },
    { name: 'Fragrant Primrose Blossom', image: 'fragrantPrimroseBlossom', type: 'survivor', rarity: 'rare' },
    { name: 'Fragrant Sweet William', image: 'fragrantSweetWilliam', type: 'survivor', rarity: 'rare' },
    { name: 'Bound Envelope', image: 'boundEnvelope', type: 'survivor', rarity: 'rare' },
    { name: 'Chalk Pouch', image: 'chalkPouch', type: 'survivor', rarity: 'common' },
    { name: 'Cream Chalk Pouch', image: 'creamChalkPouch', type: 'survivor', rarity: 'uncommon' },
    { name: 'Salt Pouch', image: 'saltPouch', type: 'survivor', rarity: 'uncommon' },
    { name: 'Black Salt Statuette', image: 'blackSaltStatuette', type: 'survivor', rarity: 'rare' },
    { name: 'Ivory Chalk Pouch', image: 'ivoryChalkPouch', type: 'survivor', rarity: 'rare' },
    { name: 'Vigo\'s Jar Of Salty Lips', image: 'jarOfSaltyLips', type: 'survivor', rarity: 'veryrare' },
    { name: 'Petrified Oak', image: 'petrifiedOak', type: 'survivor', rarity: 'veryrare' },
    { name: 'Tarnished Coin', image: 'tarnishedCoin', type: 'survivor', rarity: 'uncommon' },
    { name: 'Shiny Coin', image: 'shinyCoin', type: 'survivor', rarity: 'veryrare' },
    { name: 'Shroud of Union', image: 'shroudOfUnion', type: 'survivor', rarity: 'uncommon' },
    { name: 'Vigo\'s Shroud', image: 'vigosShroud', type: 'survivor', rarity: 'uncommon' },
    { name: 'Shroud of Binding', image: 'shroudOfBinding', type: 'survivor', rarity: 'veryrare' },
    { name: 'White Ward', image: 'wardWhite', type: 'survivor', rarity: 'veryrare' }
], COMMON_OFFERS);